setwd('/Users/dmitry/Documents/hpc-perf-analysis/memory')
df=read.csv('duplyakin-random-access.csv',header = TRUE)
colnames(df) = c("SKIP", "TN", "RATE", "AVGT", "MINT", "MAXT")
l=levels(factor(df$TN))
c=rainbow(length(l))
i=seq(from=1,to=length(l))
graphlevel=function(i) {
  subdf=subset(df,TN==l[i])
  plot(subdf$SKIP, subdf$RATE,type = "b", col = c[i],  xaxt='n', yaxt='n', ann=FALSE)
  par(new=TRUE)
}
dev.copy(png,'plot-summary.png', width = 800, height = 600)
par(oma=c(0,5,0,0))
sapply(i,graphlevel)
axis(1, at=subdf$SKIP,labels=subdf$SKIP, las=1)
axis(2, at=subdf$RATE,labels=subdf$RATE, las=2)
mtext("Skip/Block Length", side=1, line=3, cex.lab=1,las=1)
mtext("Dot Product Rate, MB/s", side=2, line=7, cex.lab=1,las=0)
title("Performance of the Dot Product")
legend(350,55000, paste("Thread Count = ", l), lty=rep(1,length(l)), lwd=rep(2.5,length(l)), col=c)
dev.off()